laravel-blog/routes/web.php
<?php

Auth::routes();

Route::get('tinker', function () {

	return view('js-playground');
	
});

// Wire up the routes for the cars
Route::resource('cars', 'CarController');

Route::get('dogs', 'DogController@indexHtml')->name('dogs.indexHtml');








// wire up the CRUD resource operations in one go
Route::resource('posts', 'PostController');










// Expose a calculator function! Note - the operator as a route param
Route::get('calculator/{operation}', 'PostController@calc');

Route::get('game', function () {
	$userName = 'Nathan';
	return view('game', compact('userName'));
});






Route::get('users', 'UserController@index')->name('users.index');

Route::get('users/{user}/{slug?}', 'UserController@show')->name('users.show');
















Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

laravel-blog/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title', 'text', 'user_id',
    ];

    public function user()
    {
    	return $this->belongsTo(User::class);
    }

    public function multiply($x, $y)
	{
		return $x * $y;
	}
}

laravel-blog/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::latest()->with('user')->paginate();
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return $post;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect()->route('posts.index');
    }
}

laravel-blog/resources/views/posts/index.blade.php
@extends('layouts.master')

@section('content')

	<h1>All posts!</h1>

	{{ $posts->links() }}

	<ul class="list-group">
		@foreach($posts as $post)
			<li class="list-group-item">
				{{ $post->title }}
				<span class="float-right badge badge-primary">
					by: 
					{{ $post->user->name }}
				</span>

				<form class="delete-form" method="post" action="{{ route('posts.destroy', $post->id) }}">
					@method('DELETE')
					@csrf
					<button class="float-right delete btn btn-danger btn-lg">
						Delete
					</button>
				</form>
			</li>
		@endforeach
	</ul>

	<script>
		var forms = document.getElementsByClassName('delete-form');

		var handler = function (event) {
			var doDelete = confirm('Are you sure you want to delete?');
			if (!doDelete)
				event.preventDefault();
		};

		for(var i=0; i<forms.length; i++)
		{
			var form = forms[i];
			form.onclick = handler;
		}
	</script>

@endsection